import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { uiStateV1Schema } from '../src/state-ui.js';
import { uiV1CustomEventSchema, uiV1EventValueSchema } from '../src/ui-v1-event.js';
import { uiV1CapabilitiesCustomEventSchema, uiV1CapabilitiesValueV1Schema } from '../src/ui-v1-capabilities.js';
import { uiDataRefV1Schema, uiDatasetV1Schema } from '../src/ui-datasets.js';
import { a2uiV1Schema } from '../src/a2ui-v1.js';
import { chartPropsV1Schema } from '../src/ui-chart.js';
import { pivotTablePropsV1Schema } from '../src/ui-pivot-table.js';
import { heatmapPropsV1Schema } from '../src/ui-heatmap.js';
import { diffViewPropsV1Schema } from '../src/ui-diff-view.js';
import { multiStepWizardPropsV1Schema, multiStepWizardStateV1Schema } from '../src/ui-multi-step-wizard.js';
import { fileUploadCardPropsV1Schema, fileUploadCardStateV1Schema, uploadedFileRefV1Schema } from '../src/ui-file-upload-card.js';
import { uiInputLimitsV1Schema } from '../src/limits.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function toConstExport(name: string, value: unknown) {
  const serialized = JSON.stringify(value, null, 2);
  return `export const ${name} = ${serialized} as const;\n`;
}

async function main() {
  const uiV1EventValueJsonSchema = uiV1EventValueSchema.toJSONSchema();
  const uiV1CustomEventJsonSchema = uiV1CustomEventSchema.toJSONSchema();
  const uiV1CapabilitiesValueV1JsonSchema = uiV1CapabilitiesValueV1Schema.toJSONSchema();
  const uiV1CapabilitiesCustomEventJsonSchema = uiV1CapabilitiesCustomEventSchema.toJSONSchema();
  const uiStateV1JsonSchema = uiStateV1Schema.toJSONSchema();
  const uiDatasetV1JsonSchema = uiDatasetV1Schema.toJSONSchema();
  const uiDataRefV1JsonSchema = uiDataRefV1Schema.toJSONSchema();
  const a2uiV1JsonSchema = a2uiV1Schema.toJSONSchema();
  const chartPropsV1JsonSchema = chartPropsV1Schema.toJSONSchema();
  const pivotTablePropsV1JsonSchema = pivotTablePropsV1Schema.toJSONSchema();
  const heatmapPropsV1JsonSchema = heatmapPropsV1Schema.toJSONSchema();
  const diffViewPropsV1JsonSchema = diffViewPropsV1Schema.toJSONSchema();
  const multiStepWizardPropsV1JsonSchema = multiStepWizardPropsV1Schema.toJSONSchema();
  const multiStepWizardStateV1JsonSchema = multiStepWizardStateV1Schema.toJSONSchema();
  const uploadedFileRefV1JsonSchema = uploadedFileRefV1Schema.toJSONSchema();
  const fileUploadCardPropsV1JsonSchema = fileUploadCardPropsV1Schema.toJSONSchema();
  const fileUploadCardStateV1JsonSchema = fileUploadCardStateV1Schema.toJSONSchema();
  const uiInputLimitsV1JsonSchema = uiInputLimitsV1Schema.toJSONSchema();

  const outPath = path.join(__dirname, '..', 'src', 'json-schema.generated.ts');
  const content = [
    '// This file is generated by scripts/generate-json-schema.ts. Do not edit by hand.\n',
    toConstExport('uiV1EventValueJsonSchema', uiV1EventValueJsonSchema),
    '\n',
    toConstExport('uiV1CustomEventJsonSchema', uiV1CustomEventJsonSchema),
    '\n',
    toConstExport('uiV1CapabilitiesValueV1JsonSchema', uiV1CapabilitiesValueV1JsonSchema),
    '\n',
    toConstExport('uiV1CapabilitiesCustomEventJsonSchema', uiV1CapabilitiesCustomEventJsonSchema),
    '\n',
    toConstExport('uiStateV1JsonSchema', uiStateV1JsonSchema),
    '\n',
    toConstExport('uiDatasetV1JsonSchema', uiDatasetV1JsonSchema),
    '\n',
    toConstExport('uiDataRefV1JsonSchema', uiDataRefV1JsonSchema),
    '\n',
    toConstExport('a2uiV1JsonSchema', a2uiV1JsonSchema),
    '\n',
    toConstExport('chartPropsV1JsonSchema', chartPropsV1JsonSchema),
    '\n',
    toConstExport('pivotTablePropsV1JsonSchema', pivotTablePropsV1JsonSchema),
    '\n',
    toConstExport('heatmapPropsV1JsonSchema', heatmapPropsV1JsonSchema),
    '\n',
    toConstExport('diffViewPropsV1JsonSchema', diffViewPropsV1JsonSchema),
    '\n',
    toConstExport('multiStepWizardPropsV1JsonSchema', multiStepWizardPropsV1JsonSchema),
    '\n',
    toConstExport('multiStepWizardStateV1JsonSchema', multiStepWizardStateV1JsonSchema),
    '\n',
    toConstExport('uploadedFileRefV1JsonSchema', uploadedFileRefV1JsonSchema),
    '\n',
    toConstExport('fileUploadCardPropsV1JsonSchema', fileUploadCardPropsV1JsonSchema),
    '\n',
    toConstExport('fileUploadCardStateV1JsonSchema', fileUploadCardStateV1JsonSchema),
    '\n',
    toConstExport('uiInputLimitsV1JsonSchema', uiInputLimitsV1JsonSchema),
    '',
  ].join('');

  await writeFile(outPath, content, 'utf8');
}

await main();
