import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { uiStateV1Schema } from '../src/state-ui.js';
import { uiV1CustomEventSchema, uiV1EventValueSchema } from '../src/ui-v1-event.js';
import { uiV1CapabilitiesCustomEventSchema, uiV1CapabilitiesValueV1Schema } from '../src/ui-v1-capabilities.js';
import { uiDataRefV1Schema, uiDatasetV1Schema } from '../src/ui-datasets.js';
import { a2uiV1Schema } from '../src/a2ui-v1.js';
import { chartPropsV1Schema } from '../src/ui-chart.js';
import { uiInputLimitsV1Schema } from '../src/limits.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function toConstExport(name: string, value: unknown) {
  const serialized = JSON.stringify(value, null, 2);
  return `export const ${name} = ${serialized} as const;\n`;
}

async function main() {
  const uiV1EventValueJsonSchema = uiV1EventValueSchema.toJSONSchema();
  const uiV1CustomEventJsonSchema = uiV1CustomEventSchema.toJSONSchema();
  const uiV1CapabilitiesValueV1JsonSchema = uiV1CapabilitiesValueV1Schema.toJSONSchema();
  const uiV1CapabilitiesCustomEventJsonSchema = uiV1CapabilitiesCustomEventSchema.toJSONSchema();
  const uiStateV1JsonSchema = uiStateV1Schema.toJSONSchema();
  const uiDatasetV1JsonSchema = uiDatasetV1Schema.toJSONSchema();
  const uiDataRefV1JsonSchema = uiDataRefV1Schema.toJSONSchema();
  const a2uiV1JsonSchema = a2uiV1Schema.toJSONSchema();
  const chartPropsV1JsonSchema = chartPropsV1Schema.toJSONSchema();
  const uiInputLimitsV1JsonSchema = uiInputLimitsV1Schema.toJSONSchema();

  const outPath = path.join(__dirname, '..', 'src', 'json-schema.generated.ts');
  const content = [
    '// This file is generated by scripts/generate-json-schema.ts. Do not edit by hand.\n',
    toConstExport('uiV1EventValueJsonSchema', uiV1EventValueJsonSchema),
    '\n',
    toConstExport('uiV1CustomEventJsonSchema', uiV1CustomEventJsonSchema),
    '\n',
    toConstExport('uiV1CapabilitiesValueV1JsonSchema', uiV1CapabilitiesValueV1JsonSchema),
    '\n',
    toConstExport('uiV1CapabilitiesCustomEventJsonSchema', uiV1CapabilitiesCustomEventJsonSchema),
    '\n',
    toConstExport('uiStateV1JsonSchema', uiStateV1JsonSchema),
    '\n',
    toConstExport('uiDatasetV1JsonSchema', uiDatasetV1JsonSchema),
    '\n',
    toConstExport('uiDataRefV1JsonSchema', uiDataRefV1JsonSchema),
    '\n',
    toConstExport('a2uiV1JsonSchema', a2uiV1JsonSchema),
    '\n',
    toConstExport('chartPropsV1JsonSchema', chartPropsV1JsonSchema),
    '\n',
    toConstExport('uiInputLimitsV1JsonSchema', uiInputLimitsV1JsonSchema),
    '',
  ].join('');

  await writeFile(outPath, content, 'utf8');
}

await main();
