import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import { uiStateV1Schema } from '../src/state-ui.js';
import { uiV1CustomEventSchema, uiV1EventValueSchema } from '../src/ui-v1-event.js';
import { uiInputLimitsV1Schema } from '../src/limits.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function toConstExport(name: string, value: unknown) {
  const serialized = JSON.stringify(value, null, 2);
  return `export const ${name} = ${serialized} as const;\n`;
}

async function main() {
  const uiV1EventValueJsonSchema = uiV1EventValueSchema.toJSONSchema();
  const uiV1CustomEventJsonSchema = uiV1CustomEventSchema.toJSONSchema();
  const uiStateV1JsonSchema = uiStateV1Schema.toJSONSchema();
  const uiInputLimitsV1JsonSchema = uiInputLimitsV1Schema.toJSONSchema();

  const outPath = path.join(__dirname, '..', 'src', 'json-schema.generated.ts');
  const content = [
    '// This file is generated by scripts/generate-json-schema.ts. Do not edit by hand.\n',
    toConstExport('uiV1EventValueJsonSchema', uiV1EventValueJsonSchema),
    '\n',
    toConstExport('uiV1CustomEventJsonSchema', uiV1CustomEventJsonSchema),
    '\n',
    toConstExport('uiStateV1JsonSchema', uiStateV1JsonSchema),
    '\n',
    toConstExport('uiInputLimitsV1JsonSchema', uiInputLimitsV1JsonSchema),
    '',
  ].join('');

  await writeFile(outPath, content, 'utf8');
}

await main();
