// This file is generated by scripts/generate-json-schema.ts. Do not edit by hand.
export const uiV1EventValueJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "componentId": {
      "type": "string",
      "minLength": 1
    },
    "eventName": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {}
    },
    "clientRequestId": {
      "type": "string",
      "minLength": 1
    },
    "baseRevision": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    }
  },
  "required": [
    "componentId",
    "eventName",
    "payload",
    "clientRequestId",
    "baseRevision"
  ],
  "additionalProperties": false
} as const;

export const uiV1CustomEventJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "CUSTOM"
    },
    "name": {
      "type": "string",
      "const": "ui.v1.event"
    },
    "value": {
      "type": "object",
      "properties": {
        "componentId": {
          "type": "string",
          "minLength": 1
        },
        "eventName": {
          "type": "string",
          "minLength": 1
        },
        "payload": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        },
        "clientRequestId": {
          "type": "string",
          "minLength": 1
        },
        "baseRevision": {
          "type": "integer",
          "minimum": 0,
          "maximum": 9007199254740991
        }
      },
      "required": [
        "componentId",
        "eventName",
        "payload",
        "clientRequestId",
        "baseRevision"
      ],
      "additionalProperties": false
    },
    "timestamp": {
      "type": "number"
    },
    "rawEvent": {}
  },
  "required": [
    "type",
    "name",
    "value"
  ],
  "additionalProperties": {}
} as const;

export const uiStateV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "v": {
      "type": "number",
      "const": 1
    },
    "components": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "minLength": 1
          },
          "schemaVersion": {
            "type": "integer",
            "minimum": 1,
            "maximum": 9007199254740991
          },
          "props": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            },
            "additionalProperties": {}
          },
          "state": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            },
            "additionalProperties": {}
          },
          "revision": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "mounts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "messageId": {
                  "type": "string",
                  "minLength": 1
                },
                "slot": {
                  "type": "string",
                  "minLength": 1
                },
                "order": {
                  "type": "integer",
                  "minimum": -9007199254740991,
                  "maximum": 9007199254740991
                }
              },
              "required": [
                "messageId",
                "slot",
                "order"
              ],
              "additionalProperties": false
            }
          },
          "status": {
            "type": "string",
            "enum": [
              "building",
              "ready",
              "error"
            ]
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "minLength": 1
              },
              "message": {
                "type": "string",
                "minLength": 1
              },
              "details": {
                "type": "object",
                "propertyNames": {
                  "type": "string"
                },
                "additionalProperties": {}
              }
            },
            "required": [
              "code",
              "message"
            ],
            "additionalProperties": {}
          }
        },
        "required": [
          "type",
          "schemaVersion",
          "props",
          "revision",
          "mounts"
        ],
        "additionalProperties": {}
      }
    },
    "datasets": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "object",
        "properties": {
          "columns": {
            "minItems": 1,
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            }
          },
          "rows": {
            "type": "array",
            "items": {
              "type": "array",
              "items": {
                "anyOf": [
                  {
                    "type": "string"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          }
        },
        "required": [
          "columns",
          "rows"
        ],
        "additionalProperties": {}
      }
    }
  },
  "required": [
    "v",
    "components"
  ],
  "additionalProperties": {}
} as const;

export const uiDatasetV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "columns": {
      "minItems": 1,
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "rows": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    }
  },
  "required": [
    "columns",
    "rows"
  ],
  "additionalProperties": {}
} as const;

export const uiDataRefV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "datasetId": {
      "type": "string",
      "minLength": 1
    }
  },
  "required": [
    "datasetId"
  ],
  "additionalProperties": false
} as const;

export const chartPropsV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "mark": {
      "type": "string",
      "enum": [
        "bar",
        "line",
        "pie"
      ]
    },
    "data": {
      "type": "object",
      "properties": {
        "columns": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "rows": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "number"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        }
      },
      "required": [
        "columns",
        "rows"
      ],
      "additionalProperties": {}
    },
    "encoding": {
      "type": "object",
      "properties": {
        "x": {
          "type": "string",
          "minLength": 1
        },
        "y": {
          "type": "string",
          "minLength": 1
        },
        "series": {
          "type": "string",
          "minLength": 1
        },
        "label": {
          "type": "string",
          "minLength": 1
        },
        "value": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "options": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1
        },
        "unit": {
          "type": "string",
          "minLength": 1
        },
        "height": {
          "type": "integer",
          "minimum": 1,
          "maximum": 2000
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "mark",
    "data",
    "encoding"
  ],
  "additionalProperties": false
} as const;

export const uiInputLimitsV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "decode": {
      "type": "object",
      "properties": {
        "maxBytes": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxDepth": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxStringLength": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        }
      },
      "additionalProperties": false
    },
    "uiEvent": {
      "type": "object",
      "properties": {
        "maxPayloadKeys": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        }
      },
      "additionalProperties": false
    },
    "uiState": {
      "type": "object",
      "properties": {
        "maxComponents": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxMountsTotal": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxDatasets": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxDatasetRows": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxDatasetColumns": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        }
      },
      "additionalProperties": false
    },
    "jsonPatch": {
      "type": "object",
      "properties": {
        "maxOps": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "maxPathLength": {
          "type": "integer",
          "minimum": 1,
          "maximum": 9007199254740991
        },
        "allowedPathPrefixes": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
} as const;
