// This file is generated by scripts/generate-json-schema.ts. Do not edit by hand.
export const uiV1EventValueJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "componentId": {
      "type": "string",
      "minLength": 1
    },
    "eventName": {
      "type": "string",
      "minLength": 1
    },
    "payload": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {}
    },
    "clientRequestId": {
      "type": "string",
      "minLength": 1
    },
    "baseRevision": {
      "type": "integer",
      "minimum": 0,
      "maximum": 9007199254740991
    }
  },
  "required": [
    "componentId",
    "eventName",
    "payload",
    "clientRequestId",
    "baseRevision"
  ],
  "additionalProperties": false
} as const;

export const uiV1CustomEventJsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "type": {
      "type": "string",
      "const": "CUSTOM"
    },
    "name": {
      "type": "string",
      "const": "ui.v1.event"
    },
    "value": {
      "type": "object",
      "properties": {
        "componentId": {
          "type": "string",
          "minLength": 1
        },
        "eventName": {
          "type": "string",
          "minLength": 1
        },
        "payload": {
          "type": "object",
          "propertyNames": {
            "type": "string"
          },
          "additionalProperties": {}
        },
        "clientRequestId": {
          "type": "string",
          "minLength": 1
        },
        "baseRevision": {
          "type": "integer",
          "minimum": 0,
          "maximum": 9007199254740991
        }
      },
      "required": [
        "componentId",
        "eventName",
        "payload",
        "clientRequestId",
        "baseRevision"
      ],
      "additionalProperties": false
    },
    "timestamp": {
      "type": "number"
    },
    "rawEvent": {}
  },
  "required": [
    "type",
    "name",
    "value"
  ],
  "additionalProperties": {}
} as const;

export const uiStateV1JsonSchema = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "v": {
      "type": "number",
      "const": 1
    },
    "components": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "minLength": 1
          },
          "schemaVersion": {
            "type": "integer",
            "minimum": 1,
            "maximum": 9007199254740991
          },
          "props": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            },
            "additionalProperties": {}
          },
          "state": {
            "type": "object",
            "propertyNames": {
              "type": "string"
            },
            "additionalProperties": {}
          },
          "revision": {
            "type": "integer",
            "minimum": 0,
            "maximum": 9007199254740991
          },
          "mounts": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "messageId": {
                  "type": "string",
                  "minLength": 1
                },
                "slot": {
                  "type": "string",
                  "minLength": 1
                },
                "order": {
                  "type": "integer",
                  "minimum": -9007199254740991,
                  "maximum": 9007199254740991
                }
              },
              "required": [
                "messageId",
                "slot",
                "order"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "type",
          "schemaVersion",
          "props",
          "revision",
          "mounts"
        ],
        "additionalProperties": {}
      }
    }
  },
  "required": [
    "v",
    "components"
  ],
  "additionalProperties": {}
} as const;
